---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: buckit
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: buckit
  metrics:
    - resource:
        name: cpu
        target: { averageUtilization: 70, type: Utilization }
      type: Resource
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
        - type: Percent
          value: 1
          periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 90
      selectPolicy: Max
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
        - type: Percent
          value: 5
          periodSeconds: 60
