apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: buckit
resources:
  - ./buckit.yaml
  - ./service.yaml
  - ./pdb.yaml
  - ./autoscaler.yaml
  - ./vaultStaticSecret.yaml
  - ./legal-exports.yaml
configMapGenerator:
  - name: buckit-init
    files:
      - ./buckit-init.sh
