apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-buckit-auth
spec:
  type: kv-v2
  path: buckit/auth
  mount: prod
  version: 4
  destination: { create: true, name: buckit-auth }
  vaultAuthRef: buckit
