name: Pulumi up
on:
  push:
    branches: [master]
    paths:
      - infra/pulumi/**

jobs:
  up:
    name: Preview
    runs-on: [self-hosted, buckit]
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4

      - name: Installing dependencies
        working-directory: ./infra/pulumi
        shell: bash {0}
        env:
          NPM_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: npm install

      - uses: pulumi/actions@v5
        env:
          PULUMI_CONFIG_PASSPHRASE: ""
        with:
          command: up
          upsert: true
          stack-name: prod
          cloud-url: s3://cloudplatform-pulumi-stacks
          work-dir: infra/pulumi
